name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    pre-commit:
        name: Pre-commit check
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout git repository
                uses: actions/checkout@v4.1.6
            -   name: Setup python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.9"
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '21'
            -   name: Pre-commit checks
                uses: pre-commit/action@v3.0.1
            -   name: pre-commit-ci-lite
                uses: pre-commit-ci/lite-action@v1.1.0
                if: always()
    build:
        runs-on: ${{ matrix.os }}
        needs: [ pre-commit ]
        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest ]
            max-parallel: 1
        steps:
            -   name: configure and run konvu-ebpf
                shell: bash
                run: |
                    set -x
                    set -e
                    curl --fail-with-body -L -O -u "$(echo ${{ secrets.KONVU_ALPHA_DL_SECRET }} | base64 -d | tr -d '[:space:]')" https://download.staging.konvu.com/binary/amd64/konvu-ebpf
                    chmod +x konvu-ebpf
                    KONVU_TOKEN=${{ secrets.KONVU_TOKEN }} KONVU_HOST=https://sensors.staging.konvu.com sudo --preserve-env=KONVU_TOKEN,KONVU_HOST ./konvu-ebpf -reporter-interval 3s -samples-per-second 2000 > /tmp/konvu.logs &
                    sleep 5
                    head /tmp/konvu.logs
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK 21
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: 21
                    architecture: x64
                    cache: 'maven'
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify

            -   name: wait for report
                shell: bash
                run: sleep 10
